;; emacs customization files
;; some are auto-generated by emacs

;; automatically added stuff


;; Org-face as per theme
;; (custom-theme-set-faces
;;  'material
;;  '(org-document-info ((t (:foreground "#81d4fa" :height 1.0))))
;;  '(org-document-info-keyword ((t (:foreground "#8bc34a" :height 1.0))))
;;  '(org-document-title ((t (:foreground "#ffffff" :weight bold :height 1.0))))
;;  '(org-level-1 ((t (:inherit outline-1 :background "#455A64" :box (:line-width 1 :style released-button) :weight bold :height 1.1))))
;;  '(org-level-2 ((t (:inherit outline-2 :background "#35575b" :box (:line-width 1 :style released-button) :height 1.1)))))
 


(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(custom-safe-themes
   (quote
    ("745f50fa29c8427309e172ec9ffb59ddd1e4a62e4871509f424ddfd854a065d2" "98cc377af705c0f2133bb6d340bf0becd08944a588804ee655809da5d8140de6" default)))
 '(ledger-reports
   (quote
    ((#("bal" 0 1
        (idx 0))
      "ledger -f /home/deadlytackler/Dropbox/Ledger/Dec29_2017onwards.ledger bal")
     (#("reg" 0 1
        (idx 1))
      "%(binary) -f %(ledger-file) reg")
     (#("payee" 0 1
        (idx 2))
      "%(binary) -f %(ledger-file) reg @%(payee)")
     (#("account" 0 1
        (idx 3))
      "%(binary) -f %(ledger-file) reg %(account)"))))
 '(org-agenda-files (quote ("~/Dropbox/diary.org")))
 '(org-plantuml-jar-path "/usr/share/plantuml/plantuml.jar")
 '(org-src-lang-modes
   (quote
    (("ocaml" . tuareg)
     ("elisp" . emacs-lisp)
     ("ditaa" . artist)
     ("asymptote" . asy)
     ("dot" . fundamental)
     ("sqlite" . sql)
     ("calc" . fundamental)
     ("C" . c)
     ("cpp" . c++)
     ("C++" . c++)
     ("screen" . shell-script)
     ("shell" . sh)
     ("bash" . sh)
     ("plantuml" . plantuml))))
 '(package-selected-packages
   (quote
    (elfeed plantuml-mode company-quickhelp which-key web-mode virtualenvwrapper validate use-package twittering-mode try theme-changer r-autoyas powerline-evil org neotree material-theme magit help-fns+ helm-projectile evil-surround evil-leader evil-indent-textobject ess-view elpy cyberpunk-theme counsel ace-window))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(aw-leading-char-face ((t (:inherit ace-jump-face-foreground :height 3.0)))))
;;==================================================================== 
