;; emacs customization files
;; some are auto-generated by emacs

;; automatically added stuff

;; themes
;; (load-theme 'leuven t)
;; (load-theme 'material t)
;; (load-theme 'material-light t)
(use-package material-theme
  :ensure t
  :config
  (progn (load-theme 'material t)
	 (load-theme 'material-light t)))

(use-package theme-changer
  :ensure t
  :config
  (progn (change-theme 'material-light 'material)))

;; (use-package cyberpunk-theme
;;   :ensure t
;;   :config
;;   (progn (load-theme 'cyberpunk t)))


;;themes-changer
;; (require 'theme-changer)
;; (change-theme 'leuven 'material)

;; Org-face as per theme
;; (custom-theme-set-faces
;;  'material
;;  '(org-document-info ((t (:foreground "#81d4fa" :height 1.0))))
;;  '(org-document-info-keyword ((t (:foreground "#8bc34a" :height 1.0))))
;;  '(org-document-title ((t (:foreground "#ffffff" :weight bold :height 1.0))))
;;  '(org-level-1 ((t (:inherit outline-1 :background "#455A64" :box (:line-width 1 :style released-button) :weight bold :height 1.1))))
;;  '(org-level-2 ((t (:inherit outline-2 :background "#35575b" :box (:line-width 1 :style released-button) :height 1.1)))))
 

;; Powerline theme
(load "~/.emacs.d/emacs-config/init-powerline.el")

;;Powerline
;; (require 'powerline)
;; (powerline-default-theme)
;; (setq powerline-default-separator 'arrow)
;; (set-face-attribute 'mode-line nil
;;                     :foreground "Black"
;;                     :background "#ff8c00"
;;                     :box nil)

;; use term instead of shell, keeping in mind python
;; (setenv "TERM" "xterm")

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ansi-color-faces-vector
   [default bold shadow italic underline bold bold-italic bold])
 '(ansi-color-names-vector
   ["#000000" "#8b0000" "#00ff00" "#ffa500" "#7b68ee" "#dc8cc3" "#93e0e3" "#dcdccc"])
 '(custom-safe-themes
   (quote
    ("98cc377af705c0f2133bb6d340bf0becd08944a588804ee655809da5d8140de6" "d6922c974e8a78378eacb01414183ce32bc8dbf2de78aabcc6ad8172547cb074" "5dc0ae2d193460de979a463b907b4b2c6d2c9c4657b2e9e66b8898d2592e3de5" default)))
 '(fci-rule-color "#383838")
 '(hl-sexp-background-color "#efebe9")
 '(org-startup-indented t)
 '(package-selected-packages
   (quote
    (projectile web-mode virtualenvwrapper counsel r-autoyas validate elpy ess-view theme-changer material-theme help-fns+ magit evil-indent-textobject evil-surround evil-leader evil which-key use-package twittering-mode try swiper neotree cyberpunk-theme ace-window)))
 '(vc-annotate-background nil)
 '(vc-annotate-color-map
   (quote
    ((20 . "#B71C1C")
     (40 . "#FF5722")
     (60 . "#FFA000")
     (80 . "#558b2f")
     (100 . "#00796b")
     (120 . "#2196f3")
     (140 . "#4527A0")
     (160 . "#B71C1C")
     (180 . "#FF5722")
     (200 . "#FFA000")
     (220 . "#558b2f")
     (240 . "#00796b")
     (260 . "#2196f3")
     (280 . "#4527A0")
     (300 . "#B71C1C")
     (320 . "#FF5722")
     (340 . "#FFA000")
     (360 . "#558b2f"))))
 '(vc-annotate-very-old-color nil))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "#263238" :foreground "#ffffff" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 100 :width normal :foundry "PfEd" :family "Ubuntu Mono"))))
 '(aw-leading-char-face ((t (:inherit ace-jump-face-foreground :height 3.0)))))
;;==================================================================== 
;; interface tweaks
(setq inhibit-startup-message t)
(tool-bar-mode -1)
